"""Umbrella Recommendation & Decision Support Schemas.

Separates automated system advisory from human management decisions.
Enforces non-prescriptive, decision-support advisory language.
"""

from datetime import datetime, timezone
from typing import List, Literal, Optional
from pydantic import BaseModel, Field


class HumanDecisionRecord(BaseModel):
    """Auditable human review and operational authorization record."""
    status: Literal["PENDING_REVIEW", "APPROVED", "MODIFIED", "REJECTED"] = "PENDING_REVIEW"
    reviewed_by: Optional[str] = Field(None, description="Username or staff ID of reviewing credit/risk officer")
    reviewed_at: Optional[datetime] = None
    approved_grace_period_days: Optional[int] = Field(None, ge=0)
    approved_actions: List[str] = Field(default_factory=list)
    reviewer_notes: Optional[str] = None


class SystemRecommendation(BaseModel):
    """Automated, explainable decision-support recommendations generated by Umbrella."""
    village_id: str
    village_name: str
    hazard_level: Literal["LOW", "MODERATE", "HIGH", "SEVERE"]
    priority_level: Literal["LOW", "MEDIUM", "HIGH", "CRITICAL"]

    # Advisory Guidance (Non-prescriptive)
    recommended_grace_period_days: int = Field(
        0, ge=0, description="Suggested repayment flexibility window for management evaluation"
    )
    operational_advisories: List[str] = Field(
        default_factory=list,
        description="Suggested operational interventions (e.g. prioritize field assessment, send advisory SMS)",
    )
    sms_advisory_template: Optional[str] = Field(
        None, description="Draft early-warning SMS text for field officers and center leaders"
    )
    priority_review_groups: List[str] = Field(
        default_factory=list, description="IDs of Joint Liability Groups recommended for priority contact"
    )
    climate_adaptation_practices: List[str] = Field(
        default_factory=list, description="Agronomic practices for community resilience"
    )

    # Risk & Sustainability Estimates
    estimated_portfolio_at_risk_inr: float = Field(
        ..., ge=0.0, description="Estimated capital volume exposed in the hazard zone"
    )
    estimated_emissions_avoided: float = Field(
        0.0,
        ge=0.0,
        description="ESTIMATED_EMISSIONS_AVOIDED: Estimated tCO2e avoided via recommended sustainable practices",
    )
    carbon_accounting_category: str = "ESTIMATED_EMISSIONS_AVOIDED"
    carbon_disclaimer: str = (
        "UNCERTIFIED OPERATIONAL ESTIMATE: Estimated emissions avoided represent activity-based proxy calculations "
        "(e.g. solar micro-irrigation vs diesel pumps). They do not constitute certified carbon credits, offsets, or guaranteed revenue."
    )


class MFIRecommendationResponse(BaseModel):
    """Complete recommendation container combining system advisory and human review workflow."""
    village_id: str
    village_name: str
    system_recommendation: SystemRecommendation
    human_decision: HumanDecisionRecord = Field(default_factory=HumanDecisionRecord)
    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    audit_notice: str = (
        "SYSTEM ADVISORY NOTICE: Umbrella recommendations provide decision support. "
        "Umbrella does not automatically execute loan rescheduling, moratoria, or contract changes without human officer authorization."
    )

    @property
    def action_summary(self) -> str:
        """Primary operational advisory summary."""
        advisories = self.system_recommendation.operational_advisories
        return advisories[0] if advisories else "Standard monitoring; no emergency action required."

